stages:
  - package
  - test-package
  - deploy

image: registry.gitlab.com/redmic-project/docker/docker-deploy

services:
  - docker:dind

variables:
  CONFLUENT_VERSION: 4.1.2
  DOCKER_DRIVER: overlay2
  STACK: confluent

docker-build-commit-non-master-branches:
  stage: package
  image: docker:stable
  variables:
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/connector-supplier
  only:
    - branches
  except:
    - master
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build -t ${IMAGE_NAME}:${CI_COMMIT_SHA} -t ${IMAGE_NAME}:${CI_COMMIT_REF_NAME}-latest .
    - docker push ${IMAGE_NAME}

docker-build-commit-master-branch:
  stage: package
  image: docker:stable
  variables:
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/connector-supplier
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build -t ${IMAGE_NAME}:${CI_COMMIT_SHA} -t ${IMAGE_NAME}:latest .
    - docker push ${IMAGE_NAME}

container-scanning:
  stage: test-package
  image: docker:stable
  variables:
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/connector-supplier
  allow_failure: true
  only:
    - branches
  script:
    - docker run -d --name db arminc/clair-db:latest
    - docker run -p 6060:6060 --link db:postgres -d --name clair arminc/clair-local-scan:v2.0.1
    - apk add -U wget ca-certificates
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker pull ${IMAGE_NAME}:${CI_COMMIT_SHA}
    - wget https://github.com/arminc/clair-scanner/releases/download/v8/clair-scanner_linux_amd64
    - mv clair-scanner_linux_amd64 clair-scanner
    - chmod +x clair-scanner
    - touch clair-whitelist.yml
    - >
      ./clair-scanner -c http://docker:6060 --ip $(hostname -i) -r gl-sast-container-report.json -l clair.log
      -w clair-whitelist.yml ${IMAGE_NAME}:${CI_COMMIT_SHA} || true
  artifacts:
    paths: [gl-sast-container-report.json]

deploy-zookeeper-dev:
  stage: deploy
  variables:
    DEPLOY_DIR_NAME: zookeeper
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    SERVICES_TO_CHECK: confluent_zk-1 confluent_zk-2 confluent_zk-3
    IMAGE_TAG: ${CONFLUENT_VERSION}
    COMPOSE_FILE: docker-compose.tmpl.yml:docker-compose.dev.yml
  script:
    - create-nets.sh kafka-net
    - deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE}
  environment:
    name: dev/zookeeper
  only:
    - branches
  except:
    - master
  when: manual

deploy-zookeeper-pro:
  stage: deploy
  variables:
    DEPLOY_DIR_NAME: zookeeper
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    SERVICES_TO_CHECK: confluent_zk-1 confluent_zk-2 confluent_zk-3
    IMAGE_TAG: ${CONFLUENT_VERSION}
    COMPOSE_FILE: docker-compose.tmpl.yml:docker-compose.prod.yml
  script:
    - create-nets.sh kafka-net
    - deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} AWS_REGION=${AWS_REGION}
  environment:
    name: pro/zookeeper
  only:
    - master
  when: manual

deploy-kafka-dev:
  stage: deploy
  variables:
    DEPLOY_DIR_NAME: kafka
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    SERVICES_TO_CHECK: confluent_kf-1 confluent_kf-2 confluent_kf-3
    IMAGE_TAG: ${CONFLUENT_VERSION}
    COMPOSE_FILE: docker-compose.tmpl.yml:docker-compose.dev.yml
    PUBLIC_HOSTNAME: ${DEV_PUBLIC_HOSTNAME}
  script:
    - deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
  environment:
    name: dev/kafka
  only:
    - branches
  except:
    - master
  when: manual

deploy-kafka-pro:
  stage: deploy
  variables:
    DEPLOY_DIR_NAME: kafka
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    SERVICES_TO_CHECK: confluent_kf-1 confluent_kf-2 confluent_kf-3
    IMAGE_TAG: ${CONFLUENT_VERSION}
    COMPOSE_FILE: docker-compose.tmpl.yml:docker-compose.prod.yml
  script:
    - deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} AWS_REGION=${AWS_REGION}
  environment:
    name: pro/kafka
  only:
    - master
  when: manual

deploy-connect-dev:
  stage: deploy
  variables:
    DEPLOY_DIR_NAME: workers
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    SERVICES_TO_CHECK: confluent_connect
    IMAGE_TAG: ${CONFLUENT_VERSION}
    COMPOSE_FILE: docker-compose.connect.tmpl.yml:docker-compose.connect.dev.yml
  services:
    - docker:dind
  script:
    - deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE}
  environment:
    name: dev/connect
  only:
    - branches
  except:
    - master
  when: manual

deploy-connect-pro:
  stage: deploy
  variables:
    DEPLOY_DIR_NAME: workers
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    SERVICES_TO_CHECK: confluent_connect
    IMAGE_TAG: ${CONFLUENT_VERSION}
    COMPOSE_FILE: docker-compose.connect.tmpl.yml:docker-compose.connect.prod.yml
  script:
    - deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE}
  environment:
    name: pro/connect
  only:
    - master
  when: manual

deploy-connector-supplier-dev:
  stage: deploy
  variables:
    DEPLOY_DIR_NAME: workers
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    SERVICES_TO_CHECK: confluent_connector-supplier
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/connector-supplier
    IMAGE_TAG: ${CI_COMMIT_SHA}
    COMPOSE_FILE: docker-compose.connector-supplier.tmpl.yml:docker-compose.connector-supplier.dev.yml
    CONNECT_ADDRS: connect:8083
  script:
    - >
      deploy.sh IMAGE_NAME=${IMAGE_NAME} IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE}
      CONNECT_ADDRS=${CONNECT_ADDRS} POSTGRES_USER=${POSTGRES_USER} POSTGRES_PASS=${POSTGRES_PASS}
  environment:
    name: dev/connector-supplier
  only:
    - branches
  except:
    - master
  when: manual

deploy-connector-supplier-pro:
  stage: deploy
  variables:
    DEPLOY_DIR_NAME: workers
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    SERVICES_TO_CHECK: confluent_connector-supplier
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/connector-supplier
    IMAGE_TAG: ${CI_COMMIT_SHA}
    COMPOSE_FILE: docker-compose.connector-supplier.tmpl.yml:docker-compose.connector-supplier.prod.yml
    CONNECT_ADDRS: connect:8083
  script:
    - >
      deploy.sh IMAGE_NAME=${IMAGE_NAME} IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE}
      CONNECT_ADDRS=${CONNECT_ADDRS} POSTGRES_USER=${POSTGRES_USER} POSTGRES_PASS=${POSTGRES_PASS}
  environment:
    name: pro/connector-supplier
  only:
    - master
  when: manual

deploy-schema-registry-dev:
  stage: deploy
  variables:
    DEPLOY_DIR_NAME: workers
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    SERVICES_TO_CHECK: confluent_schema-registry
    IMAGE_TAG: ${CONFLUENT_VERSION}
    COMPOSE_FILE: docker-compose.schema-registry.tmpl.yml:docker-compose.schema-registry.dev.yml
  script:
    - deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE}
  environment:
    name: dev/schema-registry
  only:
    - branches
  except:
    - master
  when: manual

deploy-schema-registry-pro:
  stage: deploy
  variables:
    DEPLOY_DIR_NAME: workers
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    SERVICES_TO_CHECK: confluent_schema-registry
    IMAGE_TAG: ${CONFLUENT_VERSION}
    COMPOSE_FILE: docker-compose.schema-registry.tmpl.yml:docker-compose.schema-registry.prod.yml
  script:
    - deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE}
  environment:
    name: pro/schema-registry
  only:
    - master
  when: manual

deploy-kafka-rest-dev:
  stage: deploy
  variables:
    DEPLOY_DIR_NAME: workers
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    SERVICES_TO_CHECK: confluent_kafka-rest
    IMAGE_TAG: ${CONFLUENT_VERSION}
    COMPOSE_FILE: docker-compose.kafka-rest.tmpl.yml:docker-compose.kafka-rest.dev.yml
    PUBLIC_HOSTNAME: ${DEV_PUBLIC_HOSTNAME}
  script:
    - deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
  environment:
    name: dev/kafka-rest
  only:
    - branches
  except:
    - master
  when: manual

deploy-kafka-rest-pro:
  stage: deploy
  variables:
    DEPLOY_DIR_NAME: workers
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    SERVICES_TO_CHECK: confluent_kafka-rest
    IMAGE_TAG: ${CONFLUENT_VERSION}
    COMPOSE_FILE: docker-compose.kafka-rest.tmpl.yml:docker-compose.kafka-rest.prod.yml
    PUBLIC_HOSTNAME: ${PRO_PUBLIC_HOSTNAME}
  script:
    - deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
  environment:
    name: pro/kafka-rest
  only:
    - master
  when: manual

deploy-kafka-manager-dev:
  stage: deploy
  variables:
    DEPLOY_DIR_NAME: uis
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    IMAGE_TAG: latest
    SERVICES_TO_CHECK: confluent_kafka-manager
    COMPOSE_FILE: docker-compose.kafka-manager.tmpl.yml:docker-compose.kafka-manager.dev.yml
    PUBLIC_HOSTNAME: ${DEV_PUBLIC_HOSTNAME}
  script:
    - >
      deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
      UI_AUTH=${UI_AUTH}
  environment:
    name: dev/kafka-manager
    url: https://kafkamanager.${DEV_PUBLIC_HOSTNAME}
  only:
    - branches
  except:
    - master
  when: manual

deploy-kafka-manager-pro:
  stage: deploy
  variables:
    DEPLOY_DIR_NAME: uis
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    IMAGE_TAG: latest
    SERVICES_TO_CHECK: confluent_kafka-manager
    COMPOSE_FILE: docker-compose.kafka-manager.tmpl.yml:docker-compose.kafka-manager.prod.yml
    PUBLIC_HOSTNAME: ${PRO_PUBLIC_HOSTNAME}
  script:
    - >
      deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
      UI_AUTH=${UI_AUTH}
  environment:
    name: pro/kafka-manager
    url: https://kafkamanager.${PRO_PUBLIC_HOSTNAME}
  only:
    - master
  when: manual

deploy-kafka-topics-ui-dev:
  stage: deploy
  variables:
    DEPLOY_DIR_NAME: uis
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    IMAGE_TAG: latest
    SERVICES_TO_CHECK: confluent_kafka-topics-ui
    COMPOSE_FILE: docker-compose.kafka-topics-ui.tmpl.yml:docker-compose.kafka-topics-ui.dev.yml
    PUBLIC_HOSTNAME: ${DEV_PUBLIC_HOSTNAME}
  script:
    - >
      deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
      UI_AUTH=${UI_AUTH}
  environment:
    name: dev/kafka-topics-ui
    url: https://kafkatopicsui.${DEV_PUBLIC_HOSTNAME}
  only:
    - branches
  except:
    - master
  when: manual

deploy-kafka-topics-ui-pro:
  stage: deploy
  variables:
    DEPLOY_DIR_NAME: uis
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    IMAGE_TAG: latest
    SERVICES_TO_CHECK: confluent_kafka-topics-ui
    COMPOSE_FILE: docker-compose.kafka-topics-ui.tmpl.yml:docker-compose.kafka-topics-ui.prod.yml
    PUBLIC_HOSTNAME: ${PRO_PUBLIC_HOSTNAME}
  script:
    - >
      deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
      UI_AUTH=${UI_AUTH}
  environment:
    name: pro/kafka-topics-ui
    url: https://kafkatopicsui.${PRO_PUBLIC_HOSTNAME}
  only:
    - master
  when: manual

deploy-kafka-connect-ui-dev:
  stage: deploy
  variables:
    DEPLOY_DIR_NAME: uis
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    IMAGE_TAG: latest
    SERVICES_TO_CHECK: confluent_kafka-connect-ui
    COMPOSE_FILE: docker-compose.kafka-connect-ui.tmpl.yml:docker-compose.kafka-connect-ui.dev.yml
    PUBLIC_HOSTNAME: ${DEV_PUBLIC_HOSTNAME}
  script:
    - >
      deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
      UI_AUTH=${UI_AUTH}
  environment:
    name: dev/kafka-connect-ui
    url: https://kafkaconnectui.${DEV_PUBLIC_HOSTNAME}
  only:
    - branches
  except:
    - master
  when: manual

deploy-kafka-connect-ui-pro:
  stage: deploy
  variables:
    DEPLOY_DIR_NAME: uis
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    IMAGE_TAG: latest
    SERVICES_TO_CHECK: confluent_kafka-connect-ui
    COMPOSE_FILE: docker-compose.kafka-connect-ui.tmpl.yml:docker-compose.kafka-connect-ui.prod.yml
    PUBLIC_HOSTNAME: ${PRO_PUBLIC_HOSTNAME}
  script:
    - >
      deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
      UI_AUTH=${UI_AUTH}
  environment:
    name: pro/kafka-connect-ui
    url: https://kafkaconnectui.${PRO_PUBLIC_HOSTNAME}
  only:
    - master
  when: manual

deploy-schema-registry-ui-dev:
  stage: deploy
  variables:
    DEPLOY_DIR_NAME: uis
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    IMAGE_TAG: latest
    SERVICES_TO_CHECK: confluent_schema-registry-ui
    COMPOSE_FILE: docker-compose.schema-registry-ui.tmpl.yml:docker-compose.schema-registry-ui.dev.yml
    PUBLIC_HOSTNAME: ${DEV_PUBLIC_HOSTNAME}
  script:
    - >
      deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
      UI_AUTH=${UI_AUTH}
  environment:
    name: dev/schema-registry-ui
    url: https://schemaregistryui.${DEV_PUBLIC_HOSTNAME}
  only:
    - branches
  except:
    - master
  when: manual

deploy-schema-registry-ui-pro:
  stage: deploy
  variables:
    DEPLOY_DIR_NAME: uis
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    IMAGE_TAG: latest
    SERVICES_TO_CHECK: confluent_schema-registry-ui
    COMPOSE_FILE: docker-compose.schema-registry-ui.tmpl.yml:docker-compose.schema-registry-ui.prod.yml
    PUBLIC_HOSTNAME: ${PRO_PUBLIC_HOSTNAME}
  script:
    - >
      deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
      UI_AUTH=${UI_AUTH}
  environment:
    name: pro/schema-registry-ui
    url: https://schemaregistryui.${PRO_PUBLIC_HOSTNAME}
  only:
    - master
  when: manual
