version: '3.5'

services:
  schema-registry-ui:
    image: landoop/schema-registry-ui:${IMAGE_TAG:-latest}
    hostname: schema-registry-ui
    networks:
      - kafka-net
      - traefik-net
    environment:
      SCHEMAREGISTRY_URL: http://schema-registry:${SR_PORT}
      PROXY: 'true'
      allowGlobalConfigChanges: 'true'
      allowTransitiveCompatibilities: 'true'
    healthcheck:
      test: wget --spider -S -t 3 http://localhost:${UI_PORT}
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.docker.network: traefik-net
        traefik.frontend.auth.basic.users: ${UI_AUTH}
        traefik.frontend.rule: Host:schemaregistryui.${PUBLIC_HOSTNAME}
        traefik.backend: schema-registry-ui
        traefik.port: "${UI_PORT}"
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        delay: 30s
        window: 2m
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
        reservations:
          memory: 52M

networks:
  kafka-net:
    external: true

  traefik-net:
    external: true
