version: '3.5'

services:
  kafka-connect-ui:
    image: landoop/kafka-connect-ui:${IMAGE_TAG:-latest}
    hostname: kafka-connect-ui
    networks:
      - kafka-net
    environment:
      CONNECT_URL: http://connect:${CN_PORT}
      PROXY: 'true'
      KAFKA_TOPICS_UI_ENABLED: 'true'
      KAFKA_TOPICS_UI: 'https://kafkatopicsui.${PUBLIC_HOSTNAME}'
    healthcheck:
      test: wget --spider -S -t 3 http://localhost:${UI_PORT}
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m

networks:
  kafka-net:
    external: true
