version: '3.5'

services:
  kafka-manager:
    image: giabar/gb-kafkamanager:${IMAGE_TAG:-latest}
    hostname: kafka-manager
    networks:
      - kafka-net
      - traefik-net
    environment:
      ZK_HOSTS: zk-1:${ZK_PORT},zk-2:${ZK_PORT},zk-3:${ZK_PORT}
      KM_ARGS: '-Djava.net.preferIPv4Stack=true'
    healthcheck:
      test: wget --spider -S -t 3 http://localhost:${KM_PORT}
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.docker.network: traefik-net
        traefik.frontend.auth.basic.users: ${UI_AUTH}
        traefik.frontend.rule: Host:kafkamanager.${PUBLIC_HOSTNAME}
        traefik.backend: kafka-manager
        traefik.port: "${KM_PORT}"
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        delay: 30s
        window: 2m
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          memory: 820M

networks:
  kafka-net:
    external: true

  traefik-net:
    external: true
