version: '3.5'

x-prod-environment:
  &prod-environment
  ZOOKEEPER_HEAP_OPTS: '-Xmx512m -Xms512m'

x-prod-deploy:
  &prod-deploy
  mode: replicated
  replicas: 1
  placement:
    constraints:
      - node.role == worker
  restart_policy:
    delay: 30s
    window: 2m
  resources:
    limits:
      cpus: '0.5'
      memory: 512M
    reservations:
      memory: 410M

services:
  zk-1:
    environment: *prod-environment
    deploy:
      << : *prod-deploy
      placement:
        constraints:
          - engine.labels.availability_zone == ${AWS_REGION}a

  zk-2:
    environment: *prod-environment
    deploy:
      << : *prod-deploy
      placement:
        constraints:
          - engine.labels.availability_zone == ${AWS_REGION}b

  zk-3:
    environment: *prod-environment
    deploy:
      << : *prod-deploy
      placement:
        constraints:
          - engine.labels.availability_zone == ${AWS_REGION}c

x-prod-default-volume:
  &prod-default-volume
  driver: "cloudstor:aws"
  driver_opts:
    backing: relocatable
    size: 1
    ebstype: gp2

volumes:
  zk-1-data-vol:
    << : *prod-default-volume
    name: zk-1-data-vol

  zk-1-log-vol:
    << : *prod-default-volume
    name: zk-1-log-vol

  zk-1-secrets-vol:
    name: zk-1-secrets-vol

  zk-2-data-vol:
    << : *prod-default-volume
    name: zk-2-data-vol

  zk-2-log-vol:
    << : *prod-default-volume
    name: zk-2-log-vol

  zk-2-secrets-vol:
    name: zk-2-secrets-vol

  zk-3-data-vol:
    << : *prod-default-volume
    name: zk-3-data-vol

  zk-3-log-vol:
    << : *prod-default-volume
    name: zk-3-log-vol

  zk-3-secrets-vol:
    name: zk-3-secrets-vol
