version: '3.5'

x-dev-environment:
  &dev-environment
  ZOOKEEPER_HEAP_OPTS: '-Xmx256m -Xms256m'

x-dev-deploy:
  &dev-deploy
  mode: replicated
  replicas: 1
  restart_policy:
    delay: 30s
    window: 2m
  resources:
    limits:
      cpus: '0.5'
      memory: 256M
    reservations:
      memory: 205M

services:
  zk-1:
    environment: *dev-environment
    deploy: *dev-deploy

  zk-2:
    environment: *dev-environment
    deploy: *dev-deploy

  zk-3:
    environment: *dev-environment
    deploy: *dev-deploy

volumes:
  zk-1-data-vol:
    name: zk-1-data-vol

  zk-1-log-vol:
    name: zk-1-log-vol

  zk-1-secrets-vol:
    name: zk-1-secrets-vol

  zk-2-data-vol:
    name: zk-2-data-vol

  zk-2-log-vol:
    name: zk-2-log-vol

  zk-2-secrets-vol:
    name: zk-2-secrets-vol

  zk-3-data-vol:
    name: zk-3-data-vol

  zk-3-log-vol:
    name: zk-3-log-vol

  zk-3-secrets-vol:
    name: zk-3-secrets-vol
