version: '3.5'

services:
  zk-1:
    ports:
      - ${ZK_PORT}
      - 2888
      - 3888
      - 9990
    environment:
      ZOOKEEPER_HEAP_OPTS: '-Xmx1g -Xms1g'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.workerid == 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  zk-2:
    ports:
      - ${ZK_PORT}
      - 2888
      - 3888
      - 9991
    environment:
      ZOOKEEPER_HEAP_OPTS: '-Xmx1g -Xms1g'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.workerid == 2
      restart_policy:
        condition: on-failure
        max_attempts: 3

  zk-3:
    ports:
      - ${ZK_PORT}
      - 2888
      - 3888
      - 9992
    environment:
      ZOOKEEPER_HEAP_OPTS: '-Xmx1g -Xms1g'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.workerid == 3
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  zk-1-data-vol:
    name: zk-1-data-vol
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 1
      ebstype: gp2

  zk-1-log-vol:
    name: zk-1-log-vol
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 1
      ebstype: gp2

  zk-2-data-vol:
    name: zk-2-data-vol
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 1
      ebstype: gp2

  zk-2-log-vol:
    name: zk-2-log-vol
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 1
      ebstype: gp2

  zk-3-data-vol:
    name: zk-3-data-vol
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 1
      ebstype: gp2

  zk-3-log-vol:
    name: zk-3-log-vol
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 1
      ebstype: gp2
