version: '3.5'

services:
  kf-1:
    environment:
      << : *prod-environment
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kf-1:${KF_PORT}
    deploy:
      << : *prod-deploy
      placement:
        constraints:
          - engine.labels.availability_zone == ${AWS_REGION}a

  kf-2:
    environment:
      << : *prod-environment
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kf-2:${KF_PORT}
    deploy:
      << : *prod-deploy
      placement:
        constraints:
          - engine.labels.availability_zone == ${AWS_REGION}b

  kf-3:
    environment:
      << : *prod-environment
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kf-3:${KF_PORT}
    deploy:
      << : *prod-deploy
      placement:
        constraints:
          - engine.labels.availability_zone == ${AWS_REGION}c

volumes:
  kf-1-data-vol:
    << : *prod-default-volume
    name: kf-1-data-vol

  kf-1-secrets-vol:
    name: kf-1-secrets-vol

  kf-2-data-vol:
    << : *prod-default-volume
    name: kf-2-data-vol

  kf-2-secrets-vol:
    name: kf-2-secrets-vol

  kf-3-data-vol:
    << : *prod-default-volume
    name: kf-3-data-vol

  kf-3-secrets-vol:
    name: kf-3-secrets-vol

x-prod-environment:
  &prod-environment
  - KAFKA_HEAP_OPTS=-Xmx2g -Xms2g

x-prod-deploy:
  &prod-deploy
  mode: replicated
  replicas: 1
  placement:
    constraints:
      - node.role == worker
  restart_policy:
    delay: 30s
    window: 2m
  resources:
    limits:
      cpus: '1'
      memory: 3G
    reservations:
      memory: 2458M

x-prod-default-volume:
  &prod-default-volume
  driver: "cloudstor:aws"
  driver_opts:
    backing: relocatable
    size: 500
    ebstype: st1
