version: '3.5'

services:
  kf-1:
    ports:
      - ${KF_PORT}
      - 9997
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kf-1:${KF_PORT}
      KAFKA_HEAP_OPTS: '-Xmx4g -Xms4g'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.workerid == 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  kf-2:
    ports:
      - ${KF_PORT}
      - 9998
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kf-2:${KF_PORT}
      KAFKA_HEAP_OPTS: '-Xmx4g -Xms4g'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.workerid == 2
      restart_policy:
        condition: on-failure
        max_attempts: 3

  kf-3:
    ports:
      - ${KF_PORT}
      - 9999
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kf-3:${KF_PORT}
      KAFKA_HEAP_OPTS: '-Xmx4g -Xms4g'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.workerid == 3
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  kf-1-data-vol:
    name: kf-1-data-vol
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 25
      ebstype: io1
      iops: 100

  kf-2-data-vol:
    name: kf-2-data-vol
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 25
      ebstype: io1
      iops: 100

  kf-3-data-vol:
    name: kf-3-data-vol
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 25
      ebstype: io1
      iops: 100
