version: '3.5'

x-prod-environment:
  &prod-environment
  KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://:${KF_PORT}'
  KAFKA_LISTENERS: 'PLAINTEXT://:${KF_PORT}'
  KAFKA_HEAP_OPTS: '-Xmx2g -Xms2g'

x-prod-deploy:
  &prod-deploy
  mode: replicated
  replicas: 1
  placement:
    constraints:
      - node.role == worker
  restart_policy:
    delay: 30s
    window: 2m
  resources:
    limits:
      cpus: '1'
      memory: 3G
    reservations:
      memory: 2458M

services:
  kf-1:
    environment: *prod-environment
    deploy:
      << : *prod-deploy
      placement:
        constraints:
          - engine.labels.availability_zone == ${AWS_REGION}a

  kf-2:
    environment: *prod-environment
    deploy:
      << : *prod-deploy
      placement:
        constraints:
          - engine.labels.availability_zone == ${AWS_REGION}b

  kf-3:
    environment: *prod-environment
    deploy:
      << : *prod-deploy
      placement:
        constraints:
          - engine.labels.availability_zone == ${AWS_REGION}c

x-prod-default-volume:
  &prod-default-volume
  driver: "cloudstor:aws"
  driver_opts:
    backing: relocatable
    size: 500
    ebstype: st1

volumes:
  kf-1-data-vol:
    << : *prod-default-volume
    name: kf-1-data-vol

  kf-2-data-vol:
    << : *prod-default-volume
    name: kf-2-data-vol

  kf-3-data-vol:
    << : *prod-default-volume
    name: kf-3-data-vol
