version: '3.5'

x-dev-environment:
  &dev-environment
  - KAFKA_HEAP_OPTS=-Xmx512m -Xms512m

x-dev-deploy:
  &dev-deploy
  mode: replicated
  replicas: 1
  restart_policy:
    delay: 30s
    window: 2m
  resources:
    limits:
      cpus: '1'
      memory: 1G
    reservations:
      memory: 820M

services:
  kf-1:
    environment:
      << : *dev-environment
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${PUBLIC_HOSTNAME}:1${KF_PORT}
    ports:
      - target: ${KF_PORT}
        published: 1${KF_PORT}
        mode: host
    deploy: *dev-deploy

  kf-2:
    environment:
      << : *dev-environment
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${PUBLIC_HOSTNAME}:2${KF_PORT}
    ports:
      - target: ${KF_PORT}
        published: 2${KF_PORT}
        mode: host
    deploy: *dev-deploy

  kf-3:
    environment:
      << : *dev-environment
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${PUBLIC_HOSTNAME}:3${KF_PORT}
    ports:
      - target: ${KF_PORT}
        published: 3${KF_PORT}
        mode: host
    deploy: *dev-deploy

volumes:
  kf-1-data-vol:
    name: kf-1-data-vol

  kf-1-secrets-vol:
    name: kf-1-secrets-vol

  kf-2-data-vol:
    name: kf-2-data-vol

  kf-2-secrets-vol:
    name: kf-2-secrets-vol

  kf-3-data-vol:
    name: kf-3-data-vol

  kf-3-secrets-vol:
    name: kf-3-secrets-vol
