version: '3.5'

x-dev-environment:
  &dev-environment
  KAFKA_LISTENERS: 'PLAINTEXT://:${KF_PORT},EXT://0.0.0.0:${KF_PORT_EXT}'
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXT:PLAINTEXT
  KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  KAFKA_HEAP_OPTS: '-Xmx1g -Xms1g -javaagent:/jmx_prometheus_javaagent.jar=9998:/config.yaml'

x-dev-deploy:
  &dev-deploy
  mode: replicated
  replicas: 1
  restart_policy:
    delay: 30s
    window: 2m
  resources:
    limits:
      cpus: '1'
      memory: 2G
    reservations:
      memory: 1639M

services:
  kf-1:
    environment:
      << : *dev-environment
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://:${KF_PORT},EXT://${PUBLIC_HOSTNAME}:1${KF_PORT}'
    ports:
      - target: ${KF_PORT_EXT}
        published: 1${KF_PORT}
        mode: host
    configs:
      - source: jmx-prometheus-javaagent
        target: /jmx_prometheus_javaagent.jar
      - source: jmx-prometheus-config
        target: /config.yaml
    deploy: *dev-deploy

  kf-2:
    environment:
      << : *dev-environment
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://:${KF_PORT},EXT://${PUBLIC_HOSTNAME}:2${KF_PORT}'
    ports:
      - target: ${KF_PORT_EXT}
        published: 2${KF_PORT}
        mode: host
    configs:
      - source: jmx-prometheus-javaagent
        target: /jmx_prometheus_javaagent.jar
      - source: jmx-prometheus-config
        target: /config.yaml
    deploy: *dev-deploy

  kf-3:
    environment:
      << : *dev-environment
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://:${KF_PORT},EXT://${PUBLIC_HOSTNAME}:3${KF_PORT}'
    ports:
      - target: ${KF_PORT_EXT}
        published: 3${KF_PORT}
        mode: host
    configs:
      - source: jmx-prometheus-javaagent
        target: /jmx_prometheus_javaagent.jar
      - source: jmx-prometheus-config
        target: /config.yaml
    deploy: *dev-deploy

volumes:
  kf-1-data-vol:
    name: kf-1-data-vol

  kf-1-secrets-vol:
    name: kf-1-secrets-vol

  kf-2-data-vol:
    name: kf-2-data-vol

  kf-2-secrets-vol:
    name: kf-2-secrets-vol

  kf-3-data-vol:
    name: kf-3-data-vol

  kf-3-secrets-vol:
    name: kf-3-secrets-vol

configs:
  jmx-prometheus-javaagent:
    file: ./config/jmx_prometheus_javaagent-0.3.1.jar

  jmx-prometheus-config:
    file: ./config/config.yaml
