version: '3.5'

services:
  schema-registry:
    ports:
      - '${SR_PORT}'
    environment:
      - SCHEMA_REGISTRY_HEAP_OPTS=-Xmx1g -Xms1g
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        max_attempts: 3
