version: '3.5'

services:
  connect:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 1m
        window: 3m
    environment:
      CONNECT_HEAP_OPTS: '-Xmx1g -Xms1g'
