version: '3.5'

services:
  schema-registry:
    image: confluentinc/cp-schema-registry:${IMAGE_TAG:-latest}
    hostname: schema-registry
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zk-1:${ZK_PORT},zk-2:${ZK_PORT},zk-3:${ZK_PORT}
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:${SR_PORT}
      - SCHEMA_REGISTRY_KAFKASTORE_TIMEOUT_MS=30000
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN='*'
      - SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL=backward_transitive
    networks:
      kafka-net:
        aliases:
          - schema-registry
    volumes:
      - secrets-vol:/etc/schema-registry/secrets
    healthcheck:
      test: curl -X GET http://localhost:${SR_PORT}/subjects
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 2m

networks:
  kafka-net:
    external: true
