version: '3.5'

services:
  schema-registry:
    environment:
      - SCHEMA_REGISTRY_HEAP_OPTS=-Xmx512m
    deploy:
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          memory: 820M
