version: '3.5'

services:
  connector-supplier:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - CONNECT_ADDRS=connect:${CN_PORT}
      - POSTGRES_USER
      - POSTGRES_PASS
    networks:
      - kafka-net
    volumes:
      - vol:/home/download

networks:
  kafka-net:
    external: true
